Traceback (most recent call last):
  File "/mnt/python/miniforge3/envs/jupyter-book/lib/python3.14/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/mnt/python/miniforge3/envs/jupyter-book/lib/python3.14/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/mnt/python/miniforge3/envs/jupyter-book/lib/python3.14/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/mnt/python/miniforge3/envs/jupyter-book/lib/python3.14/asyncio/base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/mnt/python/miniforge3/envs/jupyter-book/lib/python3.14/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/mnt/python/miniforge3/envs/jupyter-book/lib/python3.14/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/mnt/python/miniforge3/envs/jupyter-book/lib/python3.14/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
interval = numpy.linspace (xmin, xmax, steps+1)   # definice intervalu pro integrov√°n√≠
              # v√Ωpoƒçet vnit≈ôn√≠ch integr√°l≈Ø z Fubiniovy integrac√≠ p≈ôes druhou promƒõnnou
F = [scipy.integrate.simps(divergence[i,:], interval) for i in range(len(divergence))]
scipy.integrate.simps(F, interval)                # v√Ωpoƒçet vnƒõj≈°√≠ho integr√°lu
------------------


[31m---------------------------------------------------------------------------[39m
[31mAttributeError[39m                            Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[9][39m[32m, line 3[39m
[32m      1[39m interval = numpy.linspace (xmin, xmax, steps+[32m1[39m)   [38;5;66;03m# definice intervalu pro integrov√°n√≠[39;00m
[32m      2[39m               [38;5;66;03m# v√Ωpoƒçet vnit≈ôn√≠ch integr√°l≈Ø z Fubiniovy integrac√≠ p≈ôes druhou promƒõnnou[39;00m
[32m----> [39m[32m3[39m F = [[43mscipy[49m[43m.[49m[43mintegrate[49m[43m.[49m[43msimps[49m(divergence[i,:], interval) [38;5;28;01mfor[39;00m i [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;28mlen[39m(divergence))]
[32m      4[39m scipy.integrate.simps(F, interval)                [38;5;66;03m# v√Ωpoƒçet vnƒõj≈°√≠ho integr√°lu[39;00m

[31mAttributeError[39m: module 'scipy.integrate' has no attribute 'simps'

